export const styles: Record<string, React.CSSProperties> = {
  container: {
    height: "100vh",
    width: "100vw",
    backgroundColor: "#000",
    display: "flex",
    flexDirection: "column",
    boxSizing: "border-box",
    padding: 0,
    margin: 0,
  },
  header: {
    padding: "16px",
    textAlign: "center",
    borderBottom: "1px solid #333",
  },
  title: {
    color: "#fff",
    margin: 0,
    fontSize: "1.5rem",
  },
  chatWindow: {
    flex: 1,
    padding: "16px",
    overflowY: "auto",
    backgroundColor: "#111",
  },
  messageRow: {
    display: "flex",
    alignItems: "flex-end",
    margin: "8px 0",
  },
  icon: {
    width: 30,
    height: 30,
    borderRadius: "50%",
    marginRight: 8,
  },
  bubble: {
    maxWidth: "70%",
    padding: "10px 14px",
    borderRadius: 16,
    fontSize: 14,
    lineHeight: 1.4,
    wordBreak: "break-word",
  },
  text: {
    color: "#fff",
  },
  form: {
    display: "flex",
    padding: "12px",
    borderTop: "1px solid #333",
    backgroundColor: "#000",
  },
  input: {
    flex: 1,
    padding: "10px",
    borderRadius: 4,
    border: "1px solid #333",
    backgroundColor: "#1a1a1a",
    color: "#fff",
    outline: "none",
    fontSize: "1rem",
  },
  button: {
    marginLeft: 8,
    padding: "10px 20px",
    borderRadius: 4,
    border: "none",
    backgroundColor: "#e35205",
    color: "#fff",
    cursor: "pointer",
    fontSize: "1rem",
  },
};
